# Generated by Django 5.2 on 2025-04-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0002_product_images_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
